In [1]:
import numpy as np

In [2]:
inputs = np.random.rand(2, 1)
weights = np.random.rand(2, 1)
print(weights)
print(inputs)
output = np.matmul(weights.transpose(), inputs)
print(output)
np.tanh(output)

[[0.63193978]
 [0.30043201]]
[[0.8424255 ]
 [0.74779215]]
[[0.75702288]]


array([[0.63932003]])

In [3]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x <= y:
        return x*y
    else:
        return x/y

In [4]:
vfunc = np.vectorize(scalar_function)
x = np.arange(-5, 6).reshape(-1, 1)
y = 3
vfunc(x, y)

array([[-15],
       [-12],
       [ -9],
       [ -6],
       [ -3],
       [  0],
       [  3],
       [  6],
       [  9],
       [  1],
       [  1]])

In [5]:
metrics = []
def build_lambda(i):
  return lambda x: x+i

for i in range(3):
   print(i)
   metrics.append(build_lambda(i))
   
#     metrics.append(lambda x: x+i)
metrics[0](0)

0
1
2


0

In [10]:
num_list = [21,13,19,3,11,5,18]
num_list.sort()
print(num_list)
num_list[len(num_list) // 2] 
np.mean(num_list)


[3, 5, 11, 13, 18, 19, 21]


12.857142857142858

In [17]:
fruit_info = { 'fruit': 'apple', 'count': 2, 'price': 3.5 }
fruit_info.keys() 

dict_keys(['fruit', 'count', 'price'])

In [22]:
num_list = [1,2,3,4,5]
num_list.remove(2)
print(num_list) 


[1, 3, 4, 5]
